

services:
  db:
    image: postgres:15
    container_name: postgress_streetimpact
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bot
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_streetimpact
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetimpact_bot
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_URL: jdbc:postgresql://db:5432/bot
      DB_USER: user
      DB_PASSWORD: 123
    depends_on:
      - db

